### ISSUE TITLE
Tool is Broken

### ISSUE THREAD

**Issue by gardotd426** [arcolinux/arcolinux-tweak-tool#1]
I'm on ArcoLinuxB 20.4.10, currently using i3, and after updating I saw that ArcoLinux Tweak Tool had an update, and I was trying to see what on earth it was, especially because ArcoLinux has a bunch of cool little tools. Well, it doesn't work. I tried loading it from rofi about 4 times, the splash screen would show up after asking for my password, and then nothing. So, I tried running from a terminal. Again, lxpolkit popped up, asked for my password, which I entered, and then the splash screen showed up, and then it exited with the following errors in the terminal:
```
arcolinux-tweak-tool
list index out of range
Traceback (most recent call last):
  File "/usr/share/arcolinux-tweak-tool/arcolinux-tweak-tool.py", line 1317, in <module>
    w = Main()
  File "/usr/share/arcolinux-tweak-tool/arcolinux-tweak-tool.py", line 122, in __init__
    GUI.GUI(self, Gtk, Gdk, GdkPixbuf, base_dir, os)
  File "/usr/share/arcolinux-tweak-tool/GUI.py", line 153, in GUI
    Themer_GUI.GUI(self, Gtk, GdkPixbuf, vboxStack10, themer, Functions, base_dir)
  File "/usr/share/arcolinux-tweak-tool/Themer_GUI.py", line 71, in GUI
    awesome_lines = themer.get_awesome_themes(awesome_list)
  File "/usr/share/arcolinux-tweak-tool/themer.py", line 55, in get_awesome_themes
    theme_pos = fn._get_position(lines, "local themes = {")
  File "/usr/share/arcolinux-tweak-tool/Functions.py", line 211, in _get_position
    position = lists.index(data[0])
IndexError: list index out of range
```
I saw that some python packages also got updated, but none of the same packages that the tweak tool depends on, so I don't know.

**Comment by arcolinuxz** [comment]
well lets first talk about the very last version
today is particularly heavy 
we fixed many things
update your system v20.4.20 is the last version
report back afterwards

**Comment by gardotd426** [comment]
No, it's not. Idk if there's a testing repo, but I'm on the latest version:
```
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community                     4.9 MiB  5.66 MiB/s 00:01 [------------------------------] 100%
 multilib is up to date
 arcolinux_repo               62.6 KiB   248 KiB/s 00:00 [------------------------------] 100%
 arcolinux_repo.sig          310.0   B  0.00   B/s 00:00 [------------------------------] 100%
 arcolinux_repo_3party is up to date
 arcolinux_repo_xlarge is up to date
 chaotic-aur                 985.6 KiB  2.26 MiB/s 00:00 [------------------------------] 100%
-> Flagged Out Of Date AUR Packages:  libstrangle-git  phoronix-test-suite
 there is nothing to do
```
Notice there are no available updates. 
Output of `yay -Q | grep -i arco`:
```
yay -Q | grep -i arco
arcolinux-arc-kde 20180614-4
arcolinux-arc-themes-nico-git 20.4-1
arcolinux-bin-git 20.4-11
arcolinux-config-plasma-git 20.4-1
arcolinux-conky-collection-plasma-git 20.1-1
arcolinux-cron-git 19.12-5
arcolinux-fonts-git 19.7-3
arcolinux-grub-theme-vimix-git 20200209-2
arcolinux-keyring 20230105-1
arcolinux-kvantum-git 20.4-2
arcolinux-lightdm-gtk-greeter-plasma 1:2.0.6-1
arcolinux-lightdm-gtk-greeter-settings 1.2.2-4
arcolinux-local-xfce4-git 19.11-4
arcolinux-meta-steam 1.1.1-3
arcolinux-mirrorlist-git 20.3-1
arcolinux-mirrorlist-spinoff-git 20.3-2
arcolinux-neofetch-git 20.4-3
arcolinux-pipemenus-git 19.12-3
arcolinux-plasma-dconf-git 19.12-7
arcolinux-plasma-git 20.3-2
arcolinux-plasma-kservices-git 20.2-4
arcolinux-qt5-plasma-git 19.3-5
arcolinux-root-git 20.4-1
arcolinux-system-config-git 20.4-1
arcolinux-termite-themes-git 20.3-2
arcolinux-tweak-tool-git 20.4-25
arcolinux-variety-git 20.1-6
arcolinux-wallpapers-git 20.2-1
arcolinux-welcome-app-git 20.4-6
arcolinux-xfce-git 20.4-1
arcolinux-zsh-git 20.2-9
kcalendarcore 5.68.0-1
```
Just so you can see the versions of all my packages from arcolinux, but no, there is no available system update. Like I said, I just updated this morning, and it's showing 20.4.10

**Comment by gardotd426** [comment]
`cat /etc/lsb-release`:
```
LSB_VERSION=1.4
DISTRIB_ID=ArcoLinuxB-plasma
DISTRIB_RELEASE=v20.4.10
DISTRIB_CODENAME=ArcoLinux
DISTRIB_DESCRIPTION=ArcoLinuxB-plasma
```
screenfetch:
```
 OS: ArcoLinuxB-plasma v20.4.10 ArcoLinux
```

**Comment by BradHeff** [comment]
It can not find `local themes = {` in your config file. So you must have awesomewm config and its trying to read it, but the theme section of the lua config has been altered/removed.

**Comment by arcolinuxz** [comment]
20.4-25 is the version we have now - for arcolinux-tweak-tool-git
you have that too

**Comment by arcolinuxz** [comment]
can you come to discord - so much easier

**Comment by gardotd426** [comment]
What's the channel or invite link

**Comment by BradHeff** [comment]
https://discord.gg/R2amEEz

**Comment by BradHeff** [comment]
@gardotd426 just pushed new version of tweak tool. should solve the crash issue for you.

**Comment by gardotd426** [comment]
@BradHeff, it does indeed. However, I'm still unable to select or change any themes for either i3 or awesome under the Themes section, the dropdown is greyed out and clicking it does nothing. However, that wasn't the original issue so I'll close this for now.
